Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os

import fsspec
import ujson
import xarray as xr
from kerchunk.combine import MultiZarrToZarr
from kerchunk.hdf import SingleHdf5ToZarr
from tqdm import tqdm
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/kerchunk/hdf.py:14[0m
[1;32m     13[0m [38;5;28;01mtry[39;00m:
[0;32m---> 14[0m     [38;5;28;01mimport[39;00m [38;5;21;01mh5py[39;00m
[1;32m     15[0m [38;5;28;01mexcept[39;00m [38;5;167;01mModuleNotFoundError[39;00m:  [38;5;66;03m# pragma: no cover[39;00m

[0;31mModuleNotFoundError[0m: No module named 'h5py'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 7[0m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mxarray[39;00m [38;5;28;01mas[39;00m [38;5;21;01mxr[39;00m
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mkerchunk[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcombine[39;00m [38;5;28;01mimport[39;00m MultiZarrToZarr
[0;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mkerchunk[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhdf[39;00m [38;5;28;01mimport[39;00m SingleHdf5ToZarr
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtqdm[39;00m [38;5;28;01mimport[39;00m tqdm

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/kerchunk/hdf.py:16[0m
[1;32m     14[0m     [38;5;28;01mimport[39;00m [38;5;21;01mh5py[39;00m
[1;32m     15[0m [38;5;28;01mexcept[39;00m [38;5;167;01mModuleNotFoundError[39;00m:  [38;5;66;03m# pragma: no cover[39;00m
[0;32m---> 16[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m     17[0m         [38;5;124m"[39m[38;5;124mh5py is required for kerchunking HDF5/NetCDF4 files. Please install with [39m[38;5;124m"[39m
[1;32m     18[0m         [38;5;124m"[39m[38;5;124m`pip/conda install h5py`. See https://docs.h5py.org/en/latest/build.html [39m[38;5;124m"[39m
[1;32m     19[0m         [38;5;124m"[39m[38;5;124mfor more details.[39m[38;5;124m"[39m
[1;32m     20[0m     )
[1;32m     22[0m lggr [38;5;241m=[39m logging[38;5;241m.[39mgetLogger([38;5;124m"[39m[38;5;124mh5-to-zarr[39m[38;5;124m"[39m)
[1;32m     23[0m _HIDDEN_ATTRS [38;5;241m=[39m {  [38;5;66;03m# from h5netcdf.attrs[39;00m
[1;32m     24[0m     [38;5;124m"[39m[38;5;124mREFERENCE_LIST[39m[38;5;124m"[39m,
[1;32m     25[0m     [38;5;124m"[39m[38;5;124mCLASS[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m     31[0m     [38;5;124m"[39m[38;5;124m_NCProperties[39m[38;5;124m"[39m,
[1;32m     32[0m }

[0;31mImportError[0m: h5py is required for kerchunking HDF5/NetCDF4 files. Please install with `pip/conda install h5py`. See https://docs.h5py.org/en/latest/build.html for more details.
ImportError: h5py is required for kerchunking HDF5/NetCDF4 files. Please install with `pip/conda install h5py`. See https://docs.h5py.org/en/latest/build.html for more details.

