Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# URL pointing to a single NetCDF file
url = "s3://smn-ar-wrf/DATA/WRF/DET/2022/12/31/00/WRFDETAR_01H_20221231_00_072.nc"

# Initialize a s3 filesystem
fs = s3fs.S3FileSystem(anon=True)
# Use Xarray to open a remote NetCDF file
ds = xr.open_dataset(fs.open(url), engine="h5netcdf")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 7[0m
[1;32m      5[0m fs [38;5;241m=[39m s3fs[38;5;241m.[39mS3FileSystem(anon[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m      6[0m [38;5;66;03m# Use Xarray to open a remote NetCDF file[39;00m
[0;32m----> 7[0m ds [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m[43mfs[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43murl[49m[43m)[49m[43m,[49m[43m [49m[43mengine[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mh5netcdf[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/xarray/backends/api.py:527[0m, in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, backend_kwargs, **kwargs)[0m
[1;32m    524[0m [38;5;28;01mif[39;00m engine [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    525[0m     engine [38;5;241m=[39m plugins[38;5;241m.[39mguess_engine(filename_or_obj)
[0;32m--> 527[0m backend [38;5;241m=[39m [43mplugins[49m[38;5;241;43m.[39;49m[43mget_backend[49m[43m([49m[43mengine[49m[43m)[49m
[1;32m    529[0m decoders [38;5;241m=[39m _resolve_decoders_kwargs(
[1;32m    530[0m     decode_cf,
[1;32m    531[0m     open_backend_dataset_parameters[38;5;241m=[39mbackend[38;5;241m.[39mopen_dataset_parameters,
[0;32m   (...)[0m
[1;32m    537[0m     decode_coords[38;5;241m=[39mdecode_coords,
[1;32m    538[0m )
[1;32m    540[0m overwrite_encoded_chunks [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124moverwrite_encoded_chunks[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)

File [0;32m/usr/share/miniconda3/envs/kerchunk-cookbook-dev/lib/python3.10/site-packages/xarray/backends/plugins.py:185[0m, in [0;36mget_backend[0;34m(engine)[0m
[1;32m    183[0m     engines [38;5;241m=[39m list_engines()
[1;32m    184[0m     [38;5;28;01mif[39;00m engine [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m engines:
[0;32m--> 185[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    186[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124munrecognized engine [39m[38;5;132;01m{[39;00mengine[38;5;132;01m}[39;00m[38;5;124m must be one of: [39m[38;5;132;01m{[39;00m[38;5;28mlist[39m(engines)[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    187[0m         )
[1;32m    188[0m     backend [38;5;241m=[39m engines[engine]
[1;32m    189[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(engine, [38;5;28mtype[39m) [38;5;129;01mand[39;00m [38;5;28missubclass[39m(engine, BackendEntrypoint):

[0;31mValueError[0m: unrecognized engine h5netcdf must be one of: ['netcdf4', 'scipy', 'cfgrib', 'store', 'zarr']
ValueError: unrecognized engine h5netcdf must be one of: ['netcdf4', 'scipy', 'cfgrib', 'store', 'zarr']

